### ISSUE TITLE
include jupyter in environment file

### ISSUE THREAD

**Issue by pokarparth** [SabrinaAshik/EOSC454-Project-SabrinaAshik#1]
I tried to run the notebook in using your environment file but was not able without installing jupyter. 
Could you please add it to the environment file?

_P.S_: The readme is really informative! Nice!

**Comment by SabrinaAshik** [comment]
I didn't catch that - thank you! I added jupyter to the environment file!

**Comment by SabrinaAshik** [comment]
> I tried to run the notebook in using your environment file but was not able without installing jupyter. Could you please add it to the environment file?
> 
> _P.S_: The readme is really informative! Nice!

I didn't catch that - thank you! I added jupyter to the environment file!
