### ISSUE TITLE
typo in 1D inversion notebook

### ISSUE THREAD

**Issue by pokarparth** [SabrinaAshik/EOSC454-Project-SabrinaAshik#2]
Noticed a small typo in `1d_fdem_inversion.ipnyb`. It mentions 3 types of inversions are shown yet only L2 is present in the notebook. Just wanted to make sure it is a typo unless you meant to include other inversion types too.
 
![image_2024-04-08_200922738](https://github.com/SabrinaAshik/EOSC454-Project-SabrinaAshik/assets/85845611/711b5020-cf50-42b4-b68a-b43d48d9f9b7)

**Comment by SabrinaAshik** [comment]
> Noticed a small typo in `1d_fdem_inversion.ipnyb`. It mentions 3 types of inversions are shown yet only L2 is present in the notebook. Just wanted to make sure it is a typo unless you meant to include other inversion types too.
> 
> ![image_2024-04-08_200922738](https://private-user-images.githubusercontent.com/85845611/320709190-711b5020-cf50-42b4-b68a-b43d48d9f9b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDA4MDcsIm5iZiI6MTcxMjY0MDUwNywicGF0aCI6Ii84NTg0NTYxMS8zMjA3MDkxOTAtNzExYjUwMjAtY2Y1MC00MmI0LWI2OGEtYjQzZDQ4ZDlmOWI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA1MjgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2ZDVlMWRkMDkwM2JhMmJkZTQyOTNhYzM0NGE3ZDc2ZWI1MTk5Nzc5MmMyNGYyYWUzZDdlNDE5MWFiNDUzYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ck0Q3rY7urN4P6-TGCYeDU3JF6gOvWDspf9aJiUu8oQ)

Thank you! I didn't mean to add that there - I will update it :)
